### ISSUE TITLE
Error when restarting all instances

### ISSUE THREAD

**Issue by BigKrisch** [SeydX/homebridge-instances-platform#1]
Hello SeydX,

since version 1.2.0 the following error message occurs when restarting **all** instances:

`Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]: [2019-4-19 08:18:29] [InstancesPlatform] [INFO] Homebridge Instances: Restarting all services!
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]: (node:28234) UnhandledPromiseRejectionWarning: TypeError: this.handleSetCommand is not a function
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at accessory.services.map (/usr/local/lib/node_modules/homebridge-instances-platform/src/accessory.js:415:24)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Array.map (<anonymous>)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at BridgeAccessory.setMainSwitchState (/usr/local/lib/node_modules/homebridge-instances-platform/src/accessory.js:411:33)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Characteristic.emit (events.js:189:13)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:880:22)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Array.forEach (<anonymous>)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:820:8)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at HAPServer.emit (events.js:189:13)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]: (node:28234) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]: (node:28234) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]: (node:28234) UnhandledPromiseRejectionWarning: TypeError: this.handleSetCommand is not a function
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at accessory.services.map (/usr/local/lib/node_modules/homebridge-instances-platform/src/accessory.js:415:24)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Array.map (<anonymous>)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at BridgeAccessory.setMainSwitchState (/usr/local/lib/node_modules/homebridge-instances-platform/src/accessory.js:411:33)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Characteristic.emit (events.js:189:13)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:880:22)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Array.forEach (<anonymous>)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:820:8)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at HAPServer.emit (events.js:189:13)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]: (node:28234) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]: (node:28234) UnhandledPromiseRejectionWarning: TypeError: this.handleSetCommand is not a function
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at accessory.services.map (/usr/local/lib/node_modules/homebridge-instances-platform/src/accessory.js:415:24)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Array.map (<anonymous>)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at BridgeAccessory.setMainSwitchState (/usr/local/lib/node_modules/homebridge-instances-platform/src/accessory.js:411:33)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Characteristic.emit (events.js:189:13)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:880:22)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Array.forEach (<anonymous>)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:820:8)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at HAPServer.emit (events.js:189:13)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]: (node:28234) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]: (node:28234) UnhandledPromiseRejectionWarning: TypeError: this.handleSetCommand is not a function
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at accessory.services.map (/usr/local/lib/node_modules/homebridge-instances-platform/src/accessory.js:415:24)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Array.map (<anonymous>)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at BridgeAccessory.setMainSwitchState (/usr/local/lib/node_modules/homebridge-instances-platform/src/accessory.js:411:33)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Characteristic.emit (events.js:189:13)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:880:22)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Array.forEach (<anonymous>)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:820:8)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at HAPServer.emit (events.js:189:13)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]: (node:28234) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]: (node:28234) UnhandledPromiseRejectionWarning: TypeError: this.handleSetCommand is not a function
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at accessory.services.map (/usr/local/lib/node_modules/homebridge-instances-platform/src/accessory.js:415:24)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Array.map (<anonymous>)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at BridgeAccessory.setMainSwitchState (/usr/local/lib/node_modules/homebridge-instances-platform/src/accessory.js:411:33)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Characteristic.emit (events.js:189:13)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:880:22)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Array.forEach (<anonymous>)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:820:8)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at HAPServer.emit (events.js:189:13)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]:     at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
Apr 19 08:18:29 RaspberryPi-TWO homebridge[28234]: (node:28234) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: `5)``

**Comment by seydx** [comment]
@BigKrisch 

Thx! Pushed a new update. Should be fixed with v1.2.2

**Comment by BigKrisch** [comment]
Now it works again! As always, great support! THX !!
