### ISSUE TITLE
journalctl@1.0.0 is missing on installation

### ISSUE THREAD

**Issue by BigKrisch** [SeydX/homebridge-instances-platform#2]
Hey Seydx,

Unfortunately, the update can not be installed on 1.4.0.
It seems he does not find journalctl@1.0.0.

`sudo npm i -g homebridge-instances-platform@latest

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@seydx%2fjournalctl - Not found
npm ERR! 404 
npm ERR! 404  '@seydx/journalctl@^1.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'homebridge-instances-platform'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-22T08_35_49_612Z-debug.log`

**Comment by seydx** [comment]
@BigKrisch 

can u try update again, should be fixed now

**Comment by BigKrisch** [comment]
It works now!!  👍 THX!!
