### ISSUE TITLE
funktioniert nicht richtig

### ISSUE THREAD

**Issue by Hussamfhaily** [SeydX/homebridge-instances-platform#5]
Hi, es zeigt nur Hauptservice ( homebridgeInstances).

[2019-5-5 14:44:07] [InstancesPlatform] [ERROR] Homebridge Instances: An error occured while fetching services!
[2019-5-5 14:44:07] [InstancesPlatform] [ERROR] Error with CMD: systemctl list-unit-files | grep enabled | grep homebridge
[2019-5-5 14:44:07] [InstancesPlatform] [ERROR] Homebridge Instances: An error occured while fetching service informations!
[2019-5-5 14:44:07] [InstancesPlatform] [ERROR] Error with CMD: ps -eo pid:1,pmem:1,pcpu:1,etime:1,unit:1,state:1 --no-header | grep homebridge

**Comment by Hussamfhaily** [comment]
no service is detected.

**Comment by seydx** [comment]
@Hussamfhaily 

Can u post ur config.json pls and on which system u are running homebridge?

**Comment by Hussamfhaily** [comment]
@SeydX 
    "platforms": [
        {
            "platform": "InstancesPlatform",
            "startParam": "homebridge",
            "clearCache": false,
            "sudo": true,
            "polling": 5,
            "temperature": {
                "active": true
            },
            "notifier": {
                "active": true,
                "token": "xxxxxxxxxxxxxxxxxxxxxxxxx",
                "chatID": "xxxxxxx",
                "filter": [
                    "Main process exited",
                    "Error",
                    "error",
                    "ERROR"
                ],
                "filterInstances": [
                    "homebridge-alexa",
                    "homebridge-devolo",
                    "homebridge-config-ui-x"
                ],
                "spamInterval": 1,
                "updatesPolling": 12
            },
            "exclude": []
        },

**Comment by seydx** [comment]
@Hussamfhaily 

Can u post following in terminal and post the output pls

systemctl list-unit-files | grep enabled | grep homebridge

**Comment by seydx** [comment]
@Hussamfhaily 

And this one

ps -eo pid:1,pmem:1,pcpu:1,etime:1,unit:1,state:1 --no-header | grep homebridge

**Comment by Hussamfhaily** [comment]
@SeydX 
Hi and thank you for your cooperation.
After posting the two lines in terminal was nothing as aoutput.
But if I delete | grep homebridge the the output was:
1  0.6 0.9 23:20:59 init.scope S
2  0.0 0.0 23:20:59 - S
4  0.0 0.0 23:20:59 - I
6  0.0 0.0 23:20:59 - I
7  0.0 0.0 23:20:59 - S
8  0.0 0.0 23:20:59 - I
9  0.0 0.0 23:20:59 - I
10  0.0 0.0 23:20:59 - S
11  0.0 0.0 23:20:59 - S
12  0.0 0.0 23:20:59 - S
13  0.0 0.0 23:20:59 - S
14  0.0 0.0 23:20:59 - S
16  0.0 0.0 23:20:59 - I
17  0.0 0.0 23:20:59 - S
18  0.0 0.0 23:20:59 - S
19  0.0 0.0 23:20:59 - S
21  0.0 0.0 23:20:59 - I
22  0.0 0.0 23:20:59 - S
23  0.0 0.0 23:20:59 - S
24  0.0 0.0 23:20:59 - S
26  0.0 0.0 23:20:59 - I
27  0.0 0.0 23:20:59 - S
28  0.0 0.0 23:20:59 - I
33  0.0 0.0 23:20:59 - S
34  0.0 0.0 23:20:59 - S
35  0.0 0.0 23:20:59 - I
36  0.0 0.0 23:20:59 - S
37  0.0 0.0 23:20:59 - I
38  0.0 0.0 23:20:59 - I
39  0.0 0.0 23:20:59 - I
40  0.0 0.0 23:20:59 - I
41  0.0 0.0 23:20:59 - I
44  0.0 0.0 23:20:59 - S
45  0.0 0.0 23:20:59 - I
55  0.0 0.0 23:20:59 - I
56  0.0 0.0 23:20:59 - I
57  0.0 0.0 23:20:59 - I
58  0.0 0.0 23:20:59 - I
59  0.0 0.0 23:20:59 - S
60  0.0 0.0 23:20:59 - S
61  0.0 0.0 23:20:59 - S
62  0.0 0.0 23:20:59 - S
63  0.0 0.0 23:20:59 - S
65  0.0 0.0 23:20:59 - S
67  0.0 0.0 23:20:59 - S
68  0.0 0.0 23:20:59 - S
69  0.0 0.0 23:20:59 - I
70  0.0 0.0 23:20:58 - I
84  0.0 0.0 23:20:57 - I
101  0.5 0.0 23:20:57 systemd-journald.service S
124  0.3 0.0 23:20:57 systemd-udevd.service S
175  0.0 0.0 23:20:56 - S
182  0.0 0.1 23:20:56 - S
215  0.0 0.0 23:20:56 - I
220  0.0 0.0 23:20:56 - I
221  0.0 0.0 23:20:56 - S
264  0.3 0.0 23:20:55 systemd-timesyncd.service S
296  0.2 0.0 23:20:54 cron.service S
298  0.3 0.2 23:20:54 avahi-daemon.service S
300  0.4 0.0 23:20:54 systemd-logind.service S
306  0.3 0.0 23:20:54 dbus.service S
329  0.1 0.0 23:20:54 rng-tools.service S
335  0.1 0.0 23:20:54 dhcpcd.service S
338  0.0 0.0 23:20:54 avahi-daemon.service S
356  0.4 0.0 23:20:54 wpa_supplicant.service S
359  0.2 0.0 23:20:54 rsyslog.service S
362  0.2 0.0 23:20:54 triggerhappy.service S
401  0.2 0.0 23:20:53 dhcpcd.service S
411  0.4 0.0 23:20:53 mosquitto.service S
433  0.2 0.0 23:20:53 vncserver-x11-serviced.service S
452  1.0 0.0 23:20:53 vncserver-x11-serviced.service S
459  0.0 0.0 23:20:53 - I
466  0.1 0.0 23:20:53 getty@tty1.service S
467  0.1 0.0 23:20:53 serial-getty@ttyS0.service S
476  0.5 0.0 23:20:52 ssh.service S
506  0.0 0.0 23:20:48 - I
507  0.0 0.0 23:20:48 hciuart.service S
509  0.0 0.0 23:20:48 - I
511  0.3 0.0 23:20:48 bluetooth.service S
513  0.3 0.0 23:20:48 bluealsa.service S
527  0.0 0.0 23:20:47 - S
575  5.8 0.4 23:20:42 pm2-pi.service S
599  0.0 0.1 39:55 - I
610  0.0 0.0 23:20:34 - I
620  0.0 0.0 23:20:17 - I
1326  0.5 0.0 25:01 session-c8.scope S
1331  0.6 0.0 25:01 user@1000.service S
1334  0.1 0.0 25:01 user@1000.service S
1343  0.3 0.0 25:00 session-c8.scope S
1345  0.1 0.0 25:00 session-c8.scope S
1367  0.5 0.0 24:35 session-c9.scope S
1377  0.4 0.0 24:34 session-c9.scope S
1379  0.1 0.0 24:34 session-c9.scope S
1567  0.0 0.0 20:37 - I
1591  0.0 0.0 20:05 - I
1665  0.0 0.0 18:30 - I
2005  0.0 0.0 11:14 - I
2114 14.3 8.6 09:04 pm2-pi.service S
2136  6.7 1.5 08:52 pm2-pi.service S
2162  0.0 0.1 08:49 - I
2231  0.0 0.0 07:44 - I
2301  0.0 0.0 06:11 - I
2343  0.0 0.0 05:31 - I
2479  0.0 0.0 02:32 - I
2523  0.6 0.2 01:35 session-c10.scope S
2528  0.0 0.0 01:34 - I
2534  0.3 0.0 01:34 session-c10.scope R
2537  0.4 0.4 01:34 session-c10.scope S
3643  0.0 0.0 00:17 - I
3718  0.1 0.0 00:00 session-c10.scope R
10436  1.6 19.9 08:45:56 pm2-pi.service S
28708  0.0 0.0 02:10:59 - I

and this output from the first one:

autovt@.service                        enabled  
avahi-daemon.service                   enabled  
bluetooth.service                      enabled  
console-setup.service                  enabled  
cron.service                           enabled  
dbus-fi.w1.wpa_supplicant1.service     enabled  
dbus-org.bluez.service                 enabled  
dbus-org.freedesktop.Avahi.service     enabled  
dhcpcd.service                         enabled  
dhcpcd5.service                        enabled  
fake-hwclock.service                   enabled  
getty@.service                         enabled  
gldriver-test.service                  enabled  
hciuart.service                        enabled  
keyboard-setup.service                 enabled  
networking.service                     enabled  
pm2-pi.service                         enabled  
raspberrypi-net-mods.service           enabled  
reporter.service                       enabled  
rpi-display-backlight.service          enabled  
rsync.service                          enabled  
rsyslog.service                        enabled  
ssh.service                            enabled  
sshswitch.service                      enabled  
syslog.service                         enabled  
systemd-timesyncd.service              enabled  
triggerhappy.service                   enabled  
vncserver-x11-serviced.service         enabled  
wifi-country.service                   enabled  
wpa_supplicant.service                 enabled  
avahi-daemon.socket                    enabled  
triggerhappy.socket                    enabled  
nfs-client.target                      enabled  
remote-fs.target                       enabled  
apt-daily-upgrade.timer                enabled  
apt-daily.timer                        enabled

**Comment by Hussamfhaily** [comment]
And this is always the result

![IMG_1594](https://user-images.githubusercontent.com/18676662/57641699-edc2ae80-75b5-11e9-85b9-396cca780bc8.png)

**Comment by seydx** [comment]
@Hussamfhaily 

Sure that u are running homebridge as systemd ???

Do you have ENABLED homebridge.service units?

**Comment by Hussamfhaily** [comment]
@SeydX 
I am running homebridge using pm2. I will try using systemd.

**Comment by seydx** [comment]
this plugin is ONLY for systemd, therefore im closing this issue

**Comment by Hussamfhaily** [comment]
thank you
