### ISSUE TITLE
Other services do not appear

### ISSUE THREAD

**Issue by Hussamfhaily** [SeydX/homebridge-instances-platform#6]
Hi, Only homebridge service shows up without the other services. The plugins are installed globally in /usr/local/lib/node_modules.

**Comment by seydx** [comment]
The plugin greps all services that match your ‚startParam‘

So if your startParam is ‚homebridge‘ only all services that match this will appear

**Comment by Hussamfhaily** [comment]
Sure. But other services also with homebridge as startParam, for example homebridge-devolo or homebridge-ewelink don’t appear. I have installed them globally.
![IMG_1603](https://user-images.githubusercontent.com/18676662/57847249-50929080-77d6-11e9-8daa-5e3a9f582cf8.png)
![IMG_1604](https://user-images.githubusercontent.com/18676662/57847259-56887180-77d6-11e9-8b64-88a0e05d3fd3.png)

**Comment by seydx** [comment]
@Hussamfhaily 

The plugin DONT show plugins, it only show service units

I think you have only one service, what you mean are plugins and not services

**Comment by Hussamfhaily** [comment]
does this plugin, for example, show Alexa service installed by installing homebridge-alexa?

**Comment by seydx** [comment]
@Hussamfhaily 

This Plugin show not the plugins! It show the Service Units that are running eg homebridge

To show a plugin, you need to create its own service unit with running only the plugin

https://github.com/nfarina/homebridge/issues/1246
